# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Docker

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
        
      - name: install-libcurl
        run: sudo apt-get install -y libcurl4-openssl-dev
        
      - name: create-build-folder
        run: mkdir bin
        
      - name: build
        run: g++ LoadTestingUtility/LoadTestingUtility.cpp -lcurl -lpthread -o bin/LoadTestingUtility
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: username/load-test-utility:latest
          
      #- name: docker
      #  uses: ./  # Uses an action in the root directory
      #  with:
      #    url: 'https://www.sberbank.ru'
      #    requestsCount: '10'
