# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: setup-vstest
        uses: darenm/Setup-VSTest@v1

      - name: build
        run: msbuild LoadTestingUtility\LoadTestingUtility.vcxproj /property:Configuration=Release /property:Platform=x64

      - name: build tests
        run: msbuild LoadTestingUtility-Tests\LoadTestingUtility-Tests.vcxproj /property:Configuration=Release /property:Platform=x64
        
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
        
      - name: install-libcurl
        run: sudo apt-get install -y libcurl4-openssl-dev
        
      - name: build
        run: g++ LoadTestingUtility/LoadTestingUtility.cpp -lcurl -lpthread -o LoadTestingUtility.exe

      - name: docker
        uses: ./  # Uses an action in the root directory
        with:
          url: 'https://www.sberbank.ru'
          requestsCount: '10'